"""empty message

Revision ID: 048709e01ad7
Revises: 56911f419e23
Create Date: 2022-05-17 22:32:27.716521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '048709e01ad7'
down_revision = '56911f419e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threaded_messages', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('threaded_messages', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('threaded_messages', sa.Column('sent_to', sa.Enum('EDITOR', 'FINANCE', 'QUALITY', 'CUSTOMER', 'WRITER', 'ADMIN', name='department'), nullable=True))
    op.add_column('threaded_messages', sa.Column('sent_from', sa.Enum('EDITOR', 'FINANCE', 'QUALITY', 'CUSTOMER', 'WRITER', 'ADMIN', name='department'), nullable=True))
    op.alter_column('threaded_messages', 'timestamp',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.create_index(op.f('ix_threaded_messages_timestamp'), 'threaded_messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threaded_messages_timestamp'), table_name='threaded_messages')
    op.alter_column('threaded_messages', 'timestamp',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_column('threaded_messages', 'sent_from')
    op.drop_column('threaded_messages', 'sent_to')
    op.drop_column('threaded_messages', 'message')
    op.drop_column('threaded_messages', 'id')
    # ### end Alembic commands ###
