"""empty message

Revision ID: 0f810d150e8e
Revises: c4bbd490c6dd
Create Date: 2022-06-04 23:16:57.702035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f810d150e8e'
down_revision = 'c4bbd490c6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount_paid', sa.Numeric(precision=65, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount_paid')
    # ### end Alembic commands ###
