"""empty message

Revision ID: 10cf3f99cb1c
Revises: 9625a57a8208
Create Date: 2022-05-14 17:57:38.708920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10cf3f99cb1c'
down_revision = '9625a57a8208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('department', mysql.ENUM('EDITOR', 'FINANCE', 'QUALITY', 'CUSTOMER', 'WRITER', collation='utf8mb4_bin'), nullable=True))
    # ### end Alembic commands ###
