"""empty message

Revision ID: 21876f5f954a
Revises: b61abfd10d01
Create Date: 2022-06-04 22:10:16.092759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21876f5f954a'
down_revision = 'b61abfd10d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['writer_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('paid_orders', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paid_orders', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paid_orders', type_='foreignkey')
    op.drop_column('paid_orders', 'payment_id')
    op.drop_table('payments')
    # ### end Alembic commands ###
