"""empty message

Revision ID: 22572bb2de4e
Revises: ce248f89be64
Create Date: 2022-05-17 22:20:26.294993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22572bb2de4e'
down_revision = 'ce248f89be64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('threaded_messages_ibfk_1', 'threaded_messages', type_='foreignkey')
    op.drop_column('threaded_messages', 'recipient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threaded_messages', sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('threaded_messages_ibfk_1', 'threaded_messages', 'messages', ['recipient_id'], ['id'])
    # ### end Alembic commands ###
