"""empty message

Revision ID: 36204002f4ff
Revises: 114bf4e5ea5f
Create Date: 2022-05-10 12:50:26.522997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36204002f4ff'
down_revision = '114bf4e5ea5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('author', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('recipient', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'messages', ['recipient'], ['recipient_id'])
    op.create_foreign_key(None, 'user', 'messages', ['author'], ['sender_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'recipient')
    op.drop_column('user', 'author')
    # ### end Alembic commands ###
