"""empty message

Revision ID: 4a08d78cd4dc
Revises: cdf2533fad1c
Create Date: 2022-09-06 22:14:47.807118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a08d78cd4dc'
down_revision = 'cdf2533fad1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rating', sa.Integer(), server_default='5', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'rating')
    # ### end Alembic commands ###
