"""empty message

Revision ID: 56911f419e23
Revises: 22572bb2de4e
Create Date: 2022-05-17 22:24:13.587538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56911f419e23'
down_revision = '22572bb2de4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threaded_messages', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'threaded_messages', 'messages', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threaded_messages', type_='foreignkey')
    op.drop_column('threaded_messages', 'thread_id')
    # ### end Alembic commands ###
