"""empty message

Revision ID: 9e4e099786ca
Revises: a6026e4ed5dd
Create Date: 2022-09-10 14:45:59.229096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4e099786ca'
down_revision = 'a6026e4ed5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('amount_paid', sa.Numeric(precision=65, scale=2), server_default='0', nullable=True))
    op.add_column('writers', sa.Column('amount_fined', sa.Numeric(precision=65, scale=2), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'amount_fined')
    op.drop_column('writers', 'amount_paid')
    # ### end Alembic commands ###
