"""empty message

Revision ID: a531bc80ff17
Revises: 2e46ea4b1965
Create Date: 2022-09-25 20:59:38.020814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a531bc80ff17'
down_revision = '2e46ea4b1965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_price', sa.Numeric(precision=65, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_price')
    # ### end Alembic commands ###
