"""empty message

Revision ID: a6026e4ed5dd
Revises: ead0092c9227
Create Date: 2022-09-10 14:45:01.536299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6026e4ed5dd'
down_revision = 'ead0092c9227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('rating', sa.Integer(), server_default='5', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'rating')
    # ### end Alembic commands ###
