"""empty message

Revision ID: a8db2867acc7
Revises: 36204002f4ff
Create Date: 2022-05-10 13:13:40.131123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8db2867acc7'
down_revision = '36204002f4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.drop_column('user', 'author')
    op.drop_column('user', 'recipient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recipient', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('author', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_2', 'user', 'messages', ['author'], ['sender_id'])
    op.create_foreign_key('user_ibfk_1', 'user', 'messages', ['recipient'], ['recipient_id'])
    # ### end Alembic commands ###
