"""empty message

Revision ID: c4bbd490c6dd
Revises: 21876f5f954a
Create Date: 2022-06-04 22:24:20.775777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bbd490c6dd'
down_revision = '21876f5f954a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'user', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'orders', ['writer_id'], ['id'])
    # ### end Alembic commands ###
