"""empty message

Revision ID: ce248f89be64
Revises: 10cf3f99cb1c
Create Date: 2022-05-17 12:02:41.660843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce248f89be64'
down_revision = '10cf3f99cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threaded_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_to', sa.Enum('EDITOR', 'FINANCE', 'QUALITY', 'CUSTOMER', 'WRITER', 'ADMIN', name='department'), nullable=True),
    sa.Column('sent_from', sa.Enum('EDITOR', 'FINANCE', 'QUALITY', 'CUSTOMER', 'WRITER', 'ADMIN', name='department'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threaded_messages_timestamp'), 'threaded_messages', ['timestamp'], unique=False)
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.drop_column('messages', 'message')
    op.drop_column('messages', 'sent_from')
    op.drop_column('messages', 'timestamp')
    op.drop_column('messages', 'sent_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent_to', mysql.ENUM('EDITOR', 'FINANCE', 'QUALITY', 'CUSTOMER', 'WRITER', collation='utf8mb4_bin'), nullable=True))
    op.add_column('messages', sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
    op.add_column('messages', sa.Column('sent_from', mysql.ENUM('EDITOR', 'FINANCE', 'QUALITY', 'CUSTOMER', 'WRITER', collation='utf8mb4_bin'), nullable=True))
    op.add_column('messages', sa.Column('message', mysql.TEXT(collation='utf8mb4_bin'), nullable=True))
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_threaded_messages_timestamp'), table_name='threaded_messages')
    op.drop_table('threaded_messages')
    # ### end Alembic commands ###
