"""empty message

Revision ID: dfddd4952f35
Revises: b9d7902407c7
Create Date: 2022-08-21 13:33:05.343661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfddd4952f35'
down_revision = 'b9d7902407c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_column('messages', 'thread_id')
    # ### end Alembic commands ###
