"""empty message

Revision ID: ead0092c9227
Revises: 4a08d78cd4dc
Create Date: 2022-09-10 14:44:03.598087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead0092c9227'
down_revision = '4a08d78cd4dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('amount_paid', sa.Numeric(precision=65, scale=2), nullable=True))
    op.add_column('writers', sa.Column('amount_fined', sa.Numeric(precision=65, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'amount_fined')
    op.drop_column('writers', 'amount_paid')
    # ### end Alembic commands ###
