"""empty message

Revision ID: fde8ad6b2f1d
Revises: aebaff735dd5
Create Date: 2022-08-27 21:47:31.635863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde8ad6b2f1d'
down_revision = 'aebaff735dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read_status', sa.Enum('TRUE', 'FALSE', name='readstatus'), server_default='FALSE', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'read_status')
    # ### end Alembic commands ###
